<?xml version="1.0" ?>
<ns1:log count="2" start="0" total="2" xmlns:ns1="http://ns.dataone.org/service/types/v2.0">
  <logEntry>
    <entryId>[ENTRY-ID]</entryId>
    <identifier>PID_rygfhjvahioa</identifier>
    <ipAddress>127.0.0.1</ipAddress>
    <userAgent>DataONE-Python/[VERSION] +http://dataone.org/</userAgent>
    <subject>trusted_subj</subject>
    <event>synchronization_failed</event>
    <dateLogged>1945-04-02T00:00:00Z</dateLogged>
    <nodeIdentifier>urn:node:GMNUnitTestInstance</nodeIdentifier>
  </logEntry>
  <logEntry>
    <entryId>[ENTRY-ID]</entryId>
    <identifier>PID_rygfhjvahioa</identifier>
    <ipAddress>127.0.0.1</ipAddress>
    <userAgent>DataONE-Python/[VERSION] +http://dataone.org/</userAgent>
    <subject>trusted_subj</subject>
    <event>create</event>
    <dateLogged>2025-06-12T10:51:34Z</dateLogged>
    <nodeIdentifier>urn:node:GMNUnitTestInstance</nodeIdentifier>
  </logEntry>
</ns1:log>